# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/lllya/clion-2020.2.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/lllya/clion-2020.2.4/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lllya/IflyClassManage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lllya/IflyClassManage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/lllya/clion-2020.2.4/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/lllya/clion-2020.2.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lllya/IflyClassManage/CMakeFiles /home/lllya/IflyClassManage/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lllya/IflyClassManage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iflytek_awaken_asr

# Build rule for target.
iflytek_awaken_asr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iflytek_awaken_asr
.PHONY : iflytek_awaken_asr

# fast build rule for target.
iflytek_awaken_asr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/build
.PHONY : iflytek_awaken_asr/fast

src/awaken.o: src/awaken.c.o

.PHONY : src/awaken.o

# target to build an object file
src/awaken.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/awaken.c.o
.PHONY : src/awaken.c.o

src/awaken.i: src/awaken.c.i

.PHONY : src/awaken.i

# target to preprocess a source file
src/awaken.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/awaken.c.i
.PHONY : src/awaken.c.i

src/awaken.s: src/awaken.c.s

.PHONY : src/awaken.s

# target to generate assembly for a file
src/awaken.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/awaken.c.s
.PHONY : src/awaken.c.s

src/cJSON.o: src/cJSON.c.o

.PHONY : src/cJSON.o

# target to build an object file
src/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/cJSON.c.o
.PHONY : src/cJSON.c.o

src/cJSON.i: src/cJSON.c.i

.PHONY : src/cJSON.i

# target to preprocess a source file
src/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/cJSON.c.i
.PHONY : src/cJSON.c.i

src/cJSON.s: src/cJSON.c.s

.PHONY : src/cJSON.s

# target to generate assembly for a file
src/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/cJSON.c.s
.PHONY : src/cJSON.c.s

src/iat.o: src/iat.c.o

.PHONY : src/iat.o

# target to build an object file
src/iat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/iat.c.o
.PHONY : src/iat.c.o

src/iat.i: src/iat.c.i

.PHONY : src/iat.i

# target to preprocess a source file
src/iat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/iat.c.i
.PHONY : src/iat.c.i

src/iat.s: src/iat.c.s

.PHONY : src/iat.s

# target to generate assembly for a file
src/iat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/iat.c.s
.PHONY : src/iat.c.s

src/linuxrec.o: src/linuxrec.c.o

.PHONY : src/linuxrec.o

# target to build an object file
src/linuxrec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/linuxrec.c.o
.PHONY : src/linuxrec.c.o

src/linuxrec.i: src/linuxrec.c.i

.PHONY : src/linuxrec.i

# target to preprocess a source file
src/linuxrec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/linuxrec.c.i
.PHONY : src/linuxrec.c.i

src/linuxrec.s: src/linuxrec.c.s

.PHONY : src/linuxrec.s

# target to generate assembly for a file
src/linuxrec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/linuxrec.c.s
.PHONY : src/linuxrec.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/main.c.s
.PHONY : src/main.c.s

src/myhttp.o: src/myhttp.c.o

.PHONY : src/myhttp.o

# target to build an object file
src/myhttp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myhttp.c.o
.PHONY : src/myhttp.c.o

src/myhttp.i: src/myhttp.c.i

.PHONY : src/myhttp.i

# target to preprocess a source file
src/myhttp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myhttp.c.i
.PHONY : src/myhttp.c.i

src/myhttp.s: src/myhttp.c.s

.PHONY : src/myhttp.s

# target to generate assembly for a file
src/myhttp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myhttp.c.s
.PHONY : src/myhttp.c.s

src/myjson.o: src/myjson.c.o

.PHONY : src/myjson.o

# target to build an object file
src/myjson.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myjson.c.o
.PHONY : src/myjson.c.o

src/myjson.i: src/myjson.c.i

.PHONY : src/myjson.i

# target to preprocess a source file
src/myjson.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myjson.c.i
.PHONY : src/myjson.c.i

src/myjson.s: src/myjson.c.s

.PHONY : src/myjson.s

# target to generate assembly for a file
src/myjson.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myjson.c.s
.PHONY : src/myjson.c.s

src/myurl.o: src/myurl.c.o

.PHONY : src/myurl.o

# target to build an object file
src/myurl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myurl.c.o
.PHONY : src/myurl.c.o

src/myurl.i: src/myurl.c.i

.PHONY : src/myurl.i

# target to preprocess a source file
src/myurl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myurl.c.i
.PHONY : src/myurl.c.i

src/myurl.s: src/myurl.c.s

.PHONY : src/myurl.s

# target to generate assembly for a file
src/myurl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myurl.c.s
.PHONY : src/myurl.c.s

src/myxml.o: src/myxml.c.o

.PHONY : src/myxml.o

# target to build an object file
src/myxml.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myxml.c.o
.PHONY : src/myxml.c.o

src/myxml.i: src/myxml.c.i

.PHONY : src/myxml.i

# target to preprocess a source file
src/myxml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myxml.c.i
.PHONY : src/myxml.c.i

src/myxml.s: src/myxml.c.s

.PHONY : src/myxml.s

# target to generate assembly for a file
src/myxml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/myxml.c.s
.PHONY : src/myxml.c.s

src/play_audio.o: src/play_audio.c.o

.PHONY : src/play_audio.o

# target to build an object file
src/play_audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/play_audio.c.o
.PHONY : src/play_audio.c.o

src/play_audio.i: src/play_audio.c.i

.PHONY : src/play_audio.i

# target to preprocess a source file
src/play_audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/play_audio.c.i
.PHONY : src/play_audio.c.i

src/play_audio.s: src/play_audio.c.s

.PHONY : src/play_audio.s

# target to generate assembly for a file
src/play_audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/play_audio.c.s
.PHONY : src/play_audio.c.s

src/speech_recognizer.o: src/speech_recognizer.c.o

.PHONY : src/speech_recognizer.o

# target to build an object file
src/speech_recognizer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/speech_recognizer.c.o
.PHONY : src/speech_recognizer.c.o

src/speech_recognizer.i: src/speech_recognizer.c.i

.PHONY : src/speech_recognizer.i

# target to preprocess a source file
src/speech_recognizer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/speech_recognizer.c.i
.PHONY : src/speech_recognizer.c.i

src/speech_recognizer.s: src/speech_recognizer.c.s

.PHONY : src/speech_recognizer.s

# target to generate assembly for a file
src/speech_recognizer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/speech_recognizer.c.s
.PHONY : src/speech_recognizer.c.s

src/timer.o: src/timer.c.o

.PHONY : src/timer.o

# target to build an object file
src/timer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/timer.c.o
.PHONY : src/timer.c.o

src/timer.i: src/timer.c.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/timer.c.i
.PHONY : src/timer.c.i

src/timer.s: src/timer.c.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/timer.c.s
.PHONY : src/timer.c.s

src/tts.o: src/tts.c.o

.PHONY : src/tts.o

# target to build an object file
src/tts.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/tts.c.o
.PHONY : src/tts.c.o

src/tts.i: src/tts.c.i

.PHONY : src/tts.i

# target to preprocess a source file
src/tts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/tts.c.i
.PHONY : src/tts.c.i

src/tts.s: src/tts.c.s

.PHONY : src/tts.s

# target to generate assembly for a file
src/tts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iflytek_awaken_asr.dir/build.make CMakeFiles/iflytek_awaken_asr.dir/src/tts.c.s
.PHONY : src/tts.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... iflytek_awaken_asr"
	@echo "... src/awaken.o"
	@echo "... src/awaken.i"
	@echo "... src/awaken.s"
	@echo "... src/cJSON.o"
	@echo "... src/cJSON.i"
	@echo "... src/cJSON.s"
	@echo "... src/iat.o"
	@echo "... src/iat.i"
	@echo "... src/iat.s"
	@echo "... src/linuxrec.o"
	@echo "... src/linuxrec.i"
	@echo "... src/linuxrec.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/myhttp.o"
	@echo "... src/myhttp.i"
	@echo "... src/myhttp.s"
	@echo "... src/myjson.o"
	@echo "... src/myjson.i"
	@echo "... src/myjson.s"
	@echo "... src/myurl.o"
	@echo "... src/myurl.i"
	@echo "... src/myurl.s"
	@echo "... src/myxml.o"
	@echo "... src/myxml.i"
	@echo "... src/myxml.s"
	@echo "... src/play_audio.o"
	@echo "... src/play_audio.i"
	@echo "... src/play_audio.s"
	@echo "... src/speech_recognizer.o"
	@echo "... src/speech_recognizer.i"
	@echo "... src/speech_recognizer.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/tts.o"
	@echo "... src/tts.i"
	@echo "... src/tts.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

