#BNF+IAT 1.0 UTF-8;
!grammar call;

/*!slot <want>;
!slot <dialpre>;
!slot <dialsuf>;
!slot <contact>;

!start <callstart>;
<callstart>:[<want>]<dial>;

<want>:我想|我要|请|帮我|我想要|请帮我|要;

<dial>:<dialpre><contact>[<dialsuf>];

<dialpre>:打电话给!id(10001)|打给!id(10001)|拨打!id(10001)|拨打电话给!id(10001)|呼叫!id(10001)|
打一个电话给!id(10001)|打个电话给!id(10001)|给|拨通!id(10001)|
接通!id(10001)|呼叫!id(10001)|呼叫给!id(10001)|打!id(10001);

<dialsuf>:打电话!id(10001)|打个电话!id(10001)|打一个电话!id(10001)|
拨打电话!id(10001)|拨电话!id(10001)|0拨个电话!id(10001)|呼个电话!id(10001)|
的电话!id(10001)|的号码!id(10001)|的手机!id(10001)|
的办公电话!id(10001)|的移动号码!id(10001)|的联通号码!id(10001)|
的电信号码!id(10001)|客服电话!id(10001);

<contact>:谢嘉伟;*/

/*
!slot <todo>;
!slot <order>;

!start <t214>;
<t214>:[<todo>]<order>;

<todo>:运行!id(21301)|执行!id(21301)|进行!id(21301)|
回去!id(21302)|返回!id(21302);

<order>:人脸检测!id(21401)|检测人脸!id(21401)|
面部识别!id(21402)|识别身份!id(21402)|人脸识别!id(21402)|身份识别!id(21402)|
没电了!id(21403)|充电!id(21403)|快没电了!id(21403)|放个屁!id(21404);
*/
!slot <name>;
!slot <event>;
!slot <time>;
!slot <score>;
!start <record>;

<record>:<name>[(上课|课上|课件|下课|放学)][<event>]<score>[(分)];
<name>:
阿伟!id(00001)|
阿明!id(00002)|
朝朝!id(00004)|
谢佳薇!id(00005)|
吴珂芳!id(00006)|
肖基本!id(00007)|
张加绒!id(00008);

<time>:
上课!id(10001)|
课间!id(10002)|
下课!id(10002)|
放学!id(10003);

<event>:
睡觉|
玩手机|
迟到|
回答问题|
受表扬;


<score>:
加一|
加二|
加两|
加三|
加四|
加五|
加六|
加七|
加八|
加九|
加十|
减一|
扣一|
扣二|
减二|
扣两|
减两|
减三|
扣三|
减四|
扣四|
减五|
扣六|
减六|
减七|
扣七|
减八|
扣八|
减九|
扣九|
减十|
扣十;

